version: '3'
services:
  mysql:
    image: mysql
    container_name: ${MYSQL_HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_TCP_PORT: ${MYSQL_PORTNAME}
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
  frontend:
    build: ./frontend
    ports: 
      - '3000:3000'
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./api
    ports: 
      - '8081:8081'
    restart: always
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MYSQL_HOST: ${MYSQL_HOSTNAME}
      MYSQL_DB: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_PORT: ${MYSQL_PORTNAME}
  adminer:
    ports: 
      - '8080:8080'
    image: adminer
    restart: always
volumes:
  mysql_volume: