version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'time_user'
      MYSQL_DATABASE: 'time_db'
    restart: always
  frontend:
    build: ./frontend
    ports: 
      - '3333:3000'
    restart: always
  backend:
    build: ./api
    ports: 
      - '5555:5000'
    restart: always
    depends_on:
      - mysql
  adminer:
    ports: 
      - '8888:8080'
    image: adminer
    restart: always